### ISSUE TITLE
JS Errors

### ISSUE THREAD

**Issue by 2braincells2go** [mburakerman/toolgif#1]
Hi, very nice script. Need something like this for HTML tips.

Have installed and getting the errors show below:

```
Uncaught TypeError: $(...) is not a function(anonymous function) @ toolgif.js:132
Uncaught TypeError: refreshUrl is not a function @ toolgif.js:124
```

My page is loading jQuery already and same version you have:

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>`

This is in HTML page:

`<span class="toolgif" data-url="img/200.gif">Hover Me</span>`

The GIF appears when text is hoovered but errors are thrown. The "refreshUrl" error appears after hoovering over link in span.

Any tips on fixing the errors?

Thanks!

Woody

**Comment by mburakerman** [comment]
Hey! 
I just looked your issue and i think i solved it.
I started my plugin by using this code; 

`$(function() {
//My plugin here
})(jQuery);`

and this gives **Uncaught TypeError: $(...) is not a function** error.

To fix this i can use  Anonymous function and that solves the issue.
`(function() {
//My plugin here
})(jQuery);`

Also there is **Uncaught TypeError: refreshUrl is not a function** issue.
I suppose i know why plugin gives that error.I will try to solve it.

**Comment by 2braincells2go** [comment]
Thanks for reply.

Had a few moments to look at and solved the refreshURL issue by simply commenting that line out. Using my own gif images so do not need the function.

I totally removed the (jQuery) and error is gone. No ill effects so far.

Thanks again.

**Comment by mburakerman** [comment]
A yea.
After removing `(jQuery)` at the end error is gone.
Thanks!
